language: java
sudo: false
notifications:
  email: false
install: true
jdk: oraclejdk8
before_install:
  - pip install --user codecov
script:
  - gradle build
cache:
  directories:
    - ~/.gradle
after_success:
  - codecov
